/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NiftyRouteImport } from './routes/nifty'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as StocksSymbolRouteImport } from './routes/stocks.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NiftyRoute = NiftyRouteImport.update({
  id: '/nifty',
  path: '/nifty',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nifty': typeof NiftyRoute
  '/paper': typeof PaperRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nifty': typeof NiftyRoute
  '/paper': typeof PaperRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nifty': typeof NiftyRoute
  '/paper': typeof PaperRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nifty' | '/paper' | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nifty' | '/paper' | '/stocks/$symbol'
  id: '__root__' | '/' | '/nifty' | '/paper' | '/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NiftyRoute: typeof NiftyRoute
  PaperRoute: typeof PaperRoute
  StocksSymbolRoute: typeof StocksSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nifty': {
      id: '/nifty'
      path: '/nifty'
      fullPath: '/nifty'
      preLoaderRoute: typeof NiftyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NiftyRoute: NiftyRoute,
  PaperRoute: PaperRoute,
  StocksSymbolRoute: StocksSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
